### PR TITLE
State machine fix

### PR DESCRIPTION
**Pull request by chrishajduk84**
Beginning of merge process for state machine.

### CODE REVIEW

**Comment by wargdogs** [comment]
Like a Bosssss

**Comment by chrishajduk84** [comment]
LOL who`s up at 1:30am in the lab?

**Comment by wargdogs** [comment]
Who said I'm in the lab? Duh duh duhhhhh

**Comment by chrishajduk84** [comment]
wargdogs is only logged in on the laptop....
unless...is this Mitch?

**Comment by wargdogs** [comment]
Whoever has the UWARG email logged in can "Reply" to the email. Then it
comments as that user

**Comment by chrishajduk84** [comment]
Oh. So what you are saying, is that you aren't Mitch.

**Comment by wargdogs** [comment]
But f**king right its Mitch. All day all night in the Bay (at home
nowadays) like a Bossss

**Comment by chrishajduk84** [comment]
lol

**Pull request merged**
